/***************************************************************************
 *   Copyright (C) 2008 by Dario Freddi                                    *
 *   drf54321@yahoo.it                                                     *
 *   Copyright (C) 2008 by Lukas Appelhans   				   *
 *   l.appelhans@gmx.de							   *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.          *
 ***************************************************************************/

// This file is Auto Generated By CMake!! Don't edit it unless you're completely
// out of your goddamn mind!!

#ifndef CONFIG_H
#define CONFIG_H

/* Defines the Install Prefix */
#define INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}"

/* KDE4 Integration */
#cmakedefine KDE4_INTEGRATION 1

/* Defines the Version */

#define SHAMAN_VERSION "1.2.0-alpha1"
#define SHAMAN_CODENAME "Splitage"

/* Defines the Revision */

#define SHAMAN_REVISION "916"

#endif /*CONFIG_H*/
