/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -a shamanadaptor -m org.archlinux.shaman.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SHAMANADAPTOR_H_1214497819
#define SHAMANADAPTOR_H_1214497819

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.archlinux.shaman
 */
class ShamanAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.archlinux.shaman")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.archlinux.shaman\" >\n"
"    <method name=\"installPackage\" >\n"
"      <arg direction=\"in\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"removePackage\" >\n"
"      <arg direction=\"in\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"installPackageFromFile\" >\n"
"      <arg direction=\"in\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"doDbUpdate\" />\n"
"    <method name=\"widgetQueueToAlpmQueue\" />\n"
"    <method name=\"fullSysUpgrade\" />\n"
"    <method name=\"packageExists\" >\n"
"      <arg direction=\"in\" type=\"s\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"doStreamPackages\" />\n"
"    <signal name=\"transactionStarted\" />\n"
"    <signal name=\"transactionReleased\" />\n"
"    <signal name=\"buildingStarted\" />\n"
"    <signal name=\"buildingFinished\" />\n"
"    <signal name=\"systemIsUpToDate\" />\n"
"    <signal name=\"actionStatusChanged\" >\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </signal>\n"
"    <signal name=\"streamDbUpdatingStatus\" >\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"      <arg direction=\"out\" type=\"i\" />\n"
"    </signal>\n"
"    <signal name=\"streamTransDlProg\" >\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"      <arg direction=\"out\" type=\"i\" />\n"
"      <arg direction=\"out\" type=\"i\" />\n"
"      <arg direction=\"out\" type=\"i\" />\n"
"      <arg direction=\"out\" type=\"i\" />\n"
"    </signal>\n"
"    <signal name=\"streamTransactionProgress\" >\n"
"      <arg direction=\"out\" type=\"i\" />\n"
"    </signal>\n"
"    <signal name=\"streamPackages\" >\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </signal>\n"
"    <signal name=\"shamanReady\" />\n"
"    <signal name=\"aboutToQuit\" />\n"
"  </interface>\n"
        "")
public:
    ShamanAdaptor(QObject *parent);
    virtual ~ShamanAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void doDbUpdate();
    void doStreamPackages();
    void fullSysUpgrade();
    void installPackage(const QString &in0);
    void installPackageFromFile(const QString &in0);
    bool packageExists(const QString &in0);
    void removePackage(const QString &in0);
    void widgetQueueToAlpmQueue();
Q_SIGNALS: // SIGNALS
    void aboutToQuit();
    void actionStatusChanged(const QString &in0);
    void buildingFinished();
    void buildingStarted();
    void shamanReady();
    void streamDbUpdatingStatus(const QString &in0, int in1);
    void streamPackages(const QStringList &in0);
    void streamTransDlProg(const QString &in0, int in1, int in2, int in3, int in4);
    void streamTransactionProgress(int in0);
    void systemIsUpToDate();
    void transactionReleased();
    void transactionStarted();
};

#endif
