/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -a shamanadaptor -m org.archlinux.shaman.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "shamanadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ShamanAdaptor
 */

ShamanAdaptor::ShamanAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ShamanAdaptor::~ShamanAdaptor()
{
    // destructor
}

void ShamanAdaptor::doDbUpdate()
{
    // handle method call org.archlinux.shaman.doDbUpdate
    QMetaObject::invokeMethod(parent(), "doDbUpdate");
}

void ShamanAdaptor::doStreamPackages()
{
    // handle method call org.archlinux.shaman.doStreamPackages
    QMetaObject::invokeMethod(parent(), "doStreamPackages");
}

void ShamanAdaptor::fullSysUpgrade()
{
    // handle method call org.archlinux.shaman.fullSysUpgrade
    QMetaObject::invokeMethod(parent(), "fullSysUpgrade");
}

void ShamanAdaptor::installPackage(const QString &in0)
{
    // handle method call org.archlinux.shaman.installPackage
    QMetaObject::invokeMethod(parent(), "installPackage", Q_ARG(QString, in0));
}

void ShamanAdaptor::installPackageFromFile(const QString &in0)
{
    // handle method call org.archlinux.shaman.installPackageFromFile
    QMetaObject::invokeMethod(parent(), "installPackageFromFile", Q_ARG(QString, in0));
}

bool ShamanAdaptor::packageExists(const QString &in0)
{
    // handle method call org.archlinux.shaman.packageExists
    bool out0;
    QMetaObject::invokeMethod(parent(), "packageExists", Q_RETURN_ARG(bool, out0), Q_ARG(QString, in0));
    return out0;
}

void ShamanAdaptor::removePackage(const QString &in0)
{
    // handle method call org.archlinux.shaman.removePackage
    QMetaObject::invokeMethod(parent(), "removePackage", Q_ARG(QString, in0));
}

void ShamanAdaptor::widgetQueueToAlpmQueue()
{
    // handle method call org.archlinux.shaman.widgetQueueToAlpmQueue
    QMetaObject::invokeMethod(parent(), "widgetQueueToAlpmQueue");
}


#include "shamanadaptor.moc"
