/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -m -a shamanadaptor -i src/MainWindow.h -l MainWindow /home/drf/Development/shaman/trunk/shaman/dbus/org.archlinux.shaman.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "shamanadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ShamanAdaptor
 */

ShamanAdaptor::ShamanAdaptor(MainWindow *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ShamanAdaptor::~ShamanAdaptor()
{
    // destructor
}

void ShamanAdaptor::doDbUpdate()
{
    // handle method call org.archlinux.shaman.doDbUpdate
    parent()->doDbUpdate();
}

void ShamanAdaptor::doStreamPackages()
{
    // handle method call org.archlinux.shaman.doStreamPackages
    parent()->doStreamPackages();
}

void ShamanAdaptor::fullSysUpgrade()
{
    // handle method call org.archlinux.shaman.fullSysUpgrade
    parent()->fullSysUpgrade();
}

void ShamanAdaptor::installPackage(const QString &in0)
{
    // handle method call org.archlinux.shaman.installPackage
    parent()->installPackage(in0);
}

bool ShamanAdaptor::packageExists(const QString &in0)
{
    // handle method call org.archlinux.shaman.packageExists
    return parent()->packageExists(in0);
}

void ShamanAdaptor::removePackage(const QString &in0)
{
    // handle method call org.archlinux.shaman.removePackage
    parent()->removePackage(in0);
}

void ShamanAdaptor::widgetQueueToAlpmQueue()
{
    // handle method call org.archlinux.shaman.widgetQueueToAlpmQueue
    parent()->widgetQueueToAlpmQueue();
}


#include "shamanadaptor.moc"
